[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "node -e \"const connect = require('connect'), http = require('http'), serveStatic = require('serve-static'); const app = connect(); app.use(serveStatic('dist')); app.use((req, res) => { res.writeHead(200, { 'Content-Type': 'text/html' }); res.end(require('fs').readFileSync('dist/index.html')); }); http.createServer(app).listen(process.env.PORT || 3000);\""
installRuntimeDeps = ["connect", "serve-static"] 