[phases.setup]
nixPkgs = ["nodejs", "yarn"]

[phases.install]
cmds = [
  "cd frontend && yarn install",
  "cd backend && yarn install"
]

[phases.build]
cmds = [
  "cd frontend && yarn build",
  "cd backend && yarn build"
]

[start]
cmd = "cd backend && yarn start"

[frontend]
cmd = "node -e \"const connect = require('connect'), http = require('http'), serveStatic = require('serve-static'); const app = connect(); app.use(serveStatic('frontend/dist')); app.use((req, res) => { res.writeHead(200, { 'Content-Type': 'text/html' }); res.end(require('fs').readFileSync('frontend/dist/index.html')); }); http.createServer(app).listen(process.env.PORT || 3000);\""
installRuntimeDeps = ["connect", "serve-static"] 